<a href="https://colab.research.google.com/github/Amanshrivastav06/Python/blob/main/Numpy(29_march_25).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy - Numbers in python called numpy
import numpy as np

In [ ]:
list1 = [1,2,3,45,4]

In [ ]:
list1

[1, 2, 3, 45, 4]

In [ ]:
# convert list into array
array = np.array(list1)

In [ ]:
print(array)

[ 1  2  3 45  4]


In [ ]:
# array = a data structure that stores a collection of elements of the same data type
# in contiguous memory locations, allowing efficient access and manipulation of data.
# array Types
# one dimension
# two dimension
# three dimension
# array contain row and column
# array is the matrix
# matrix is the combination of row and column

In [ ]:
 # one dimension  array
one_dim = np.array([1,2,3,4,5])

In [ ]:
print(one_dim)

[1 2 3 4 5]


In [ ]:
# how to check the row and column of the matrix
one_dim.shape

(5,)

In [ ]:
# two dimension matrix - is combination of one dim matrix
two_dim = np.array([[1,2,3,4,5],[4,6,7,8,8],[2,6,7,88,8]])

In [ ]:
print(two_dim)

[[ 1  2  3  4  5]
 [ 4  6  7  8  8]
 [ 2  6  7 88  8]]


In [ ]:
two_dim.shape

(3, 5)

In [ ]:
# three dimension matrix
# it is the combination of two dimension matrix
three_dim = np.array([[[1,2,3,4,5],[1,4,6,7,8]],[[1,5,6,7,8],[3,4,6,8,9]]])

In [ ]:
print(three_dim)

[[[1 2 3 4 5]
  [1 4 6 7 8]]

 [[1 5 6 7 8]
  [3 4 6 8 9]]]


In [ ]:
three_dim.shape

(2, 2, 5)

In [ ]:
# indexing and slicing
# indexing
one_dim

array([1, 2, 3, 4, 5])

In [ ]:
one_dim[2:4]

array([3, 4])

In [ ]:
# indexing and slicing in two d
two_dim


array([[ 1,  2,  3,  4,  5],
       [ 4,  6,  7,  8,  8],
       [ 2,  6,  7, 88,  8]])

In [ ]:
# finding 8 value , first write row no then column
two_dim[1,3]

np.int64(8)

In [ ]:
# i need 7,8 and 7,88 , note - first write row no then column no
two_dim[1:3, 2:4]

array([[ 7,  8],
       [ 7, 88]])

In [ ]:
two_dim[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [ ]:
# indexing and slicing in three d
# matrix, row and column

three_dim

array([[[1, 2, 3, 4, 5],
        [1, 4, 6, 7, 8]],

       [[1, 5, 6, 7, 8],
        [3, 4, 6, 8, 9]]])

In [ ]:
three_dim[1]

array([[1, 5, 6, 7, 8],
       [3, 4, 6, 8, 9]])

In [ ]:
three_dim[1,1,2]

np.int64(6)

In [ ]:
# array inspection
# shape
# len
# dim
# astype
# dtype.name

In [ ]:
# shape
three_dim.shape

(2, 2, 5)

In [ ]:
# len
len(three_dim)

2

In [ ]:
three_dim.ndim

3

In [ ]:
two_dim.ndim

2

In [ ]:
# dtype.name
three_dim.dtype

dtype('int64')

In [ ]:
three_dim.dtype.name

'int64'

In [ ]:
# astype
# change the data type
three_dim = three_dim.astype(float)

In [ ]:
three_dim

array([[[1., 2., 3., 4., 5.],
        [1., 4., 6., 7., 8.]],

       [[1., 5., 6., 7., 8.],
        [3., 4., 6., 8., 9.]]])

In [ ]:
# intial placeholder
# type of way to make a matrix
# zeros matrix
# by default its data type is float
np.zeros((1,2))

array([[0., 0.]])

In [ ]:
np.zeros((1,2), dtype = int)

array([[0, 0]])

In [ ]:
# ones matrix
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# empty matrix
np.empty((6,2))

array([[6.89656192e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
# full matrix
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
# random. random
np.random.random((3,4))

array([[0.97638035, 0.15737305, 0.4831048 , 0.74396238],
       [0.12125439, 0.44695179, 0.94352665, 0.63983876],
       [0.89740316, 0.15180443, 0.20201403, 0.36659597]])

In [ ]:
# random.randint - yha pe 2,4 ka mtlab 2 aur 4 ke bich me hi numbers aayega
np.random.randint(2,4,(3,4))

array([[3, 3, 2, 2],
       [3, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# arithmetic operation
# sum , min, max, square, divide
one = np.random.randint(2,5,(2,3))

In [ ]:
two = np.random.randint(2,4,(2,3))

In [ ]:
one

array([[3, 2, 4],
       [2, 3, 4]])

In [ ]:
two

array([[3, 3, 2],
       [3, 3, 2]])

In [ ]:
# addition aise hi sb perform karenege , bs order same hona chaiye
one + two

array([[6, 5, 6],
       [5, 6, 6]])

In [ ]:
# by use of numpy
np.add(one, two)

array([[6, 5, 6],
       [5, 6, 6]])

In [ ]:
# aggregate function
# sum, min, max, mean, cumsum, standard deviation, variance

In [ ]:
np.sum(one)

np.int64(18)

In [ ]:
# with axis value = 0 , add rows values
np.sum(one, axis = 0)

array([5, 5, 8])

In [ ]:
# with axis value = 1 , add column values
np.sum(one,axis = 1)

array([9, 9])